CREATE TABLE Library
(
ID_library INT(3) UNSIGNED UNIQUE NOT NULL, 
location VARCHAR(20) NOT NULL, 
item_amount INT UNSIGNED NOT NULL,
PRIMARY KEY(ID_library)
);

CREATE TABLE Staff
(
ID_staff INT(5) UNSIGNED UNIQUE NOT NULL,
name VARCHAR(50) NOT NULL,
card_ID CHAR(8) NOT NULL,
address VARCHAR(200) NOT NULL,
email VARCHAR(30) NOT NULL,
phone CHAR(8) NOT NULL,
ID_library INT(3) UNSIGNED NOT NULL,
position VARCHAR(20) NOT NULL,
join_date DATE NOT NULL,
salary DECIMAL(7,1) UNSIGNED NOT NULL,
PRIMARY KEY(ID_staff),
FOREIGN KEY(ID_library) REFERENCES Library(ID_library)
);

CREATE TABLE Collection
(
ISBN INT(13) UNSIGNED UNIQUE NOT NULL,
name VARCHAR(100) NOT NULL,
type CHAR(2) NOT NULL,
author VARCHAR(50),
publisher VARCHAR(50),
language VARCHAR(20) NOT NULL,
ID_search INT(7) UNSIGNED NOT NULL,
category VARCHAR(20) NOT NULL,
PRIMARY KEY(ISBN)
);

CREATE TABLE Item
(
ID_item INT(10) UNSIGNED UNIQUE NOT NULL,
ID_library INT(3) UNSIGNED NOT NULL,
ISBN INT(13) UNSIGNED NOT NULL,
status INT(2) UNSIGNED NOT NULL,
bought_date DATE NOT NULL,
cost DECIMAL(4,1),
PRIMARY KEY(ID_item),
FOREIGN KEY(ID_library) REFERENCES Library(ID_library),
FOREIGN KEY(ISBN) REFERENCES Collection(ISBN)
);


CREATE TABLE Member
(
ID_member INT(10) UNSIGNED UNIQUE NOT NULL,
name VARCHAR(50) NOT NULL,
card_ID CHAR(8) NOT NULL,
address VARCHAR(200) NOT NULL,
penalty NUMERIC(4,1) DEFAULT 0,
PRIMARY KEY(ID_member)
);

CREATE TABLE Slot
(
ID_slot INT(1) UNSIGNED NOT NULL,
ID_member INT(10) UNSIGNED NOT NULL,
ID_item INT(10) UNSIGNED,
borrow_date DATE,
return_date DATE,
PRIMARY KEY(ID_member, ID_slot),
FOREIGN KEY(ID_member) REFERENCES Member(ID_member),
FOREIGN KEY(ID_item) REFERENCES Item(ID_item)
)